resources:
  varname_crosswalk: 'backend/scraper/varnames_crosswalk.csv'

sources:
  mpv:
      url: https://mappingpoliceviolence.org/s/MPVDatasetDownload.xlsx
      type: news article
  cpdp:
      url: https://github.com/invinst/chicago-police-data/raw/master/data/unified_data.zip
      type: government record
tables:
  report:
    required:
      - record_id
      - data_source_id
      - record_type
      - attachments_available
    optional:
      - null
  incident:
    required:
      - record_id
      - incident_date
      - incident_time
      - description
      - perpetrator
      - department_present
    optional:
      - incident_type
  victim:
    required:
      - null
    optional:
      - victim_name_full
      - victim_sex
      - victim_age
      - victim_race
  death:
    required:
      - death_location_street_address
      - death_location_city
    optional:
      - death_manner